### ISSUE TITLE
IM and DD formulations

### ISSUE THREAD

**Issue by shmouses** [LeilaMousapour/Brain-Computer-Interface-#12]
Hi @LeilaMousapour, 
Although you have formulations and some parameters in your TMs, I didn't quit found their relationship and the implementation of these theories in your IMs and DDs towards satisfying your GSs. To be more specific, I found DDs and IMs here very abstract and more qualitative than very specific with clear mathematical relationships exactly indicating the input variables and output variables. However, at the end this is my point of view and just a suggestion.

**Comment by LeilaMousapour** [comment]
Hi @shmouses,
Thank you for reading and reviewing my SRS so carelufy. Your comments were really insightful!
Regarding this specific comment, for implementation of each of the instance models, I use a package (fieldtrip toolbox) which already has implemented the math behind them as the math behind every IM is very extensive and complicated and is over the scope of my project I suppose. That is the reason I explained them more qualitative in terms of what are the inout and outputs and what the IM does rather than going into detailed math. For example, I don't go into the mathematical details of head model generation and the math behind boundary element method (BEM) even for my master's project. I only utilize them  somehow as black boxes.
@smiths 
Dr. Smith, I wonder if you think more mathematical details are needed in the SRS document?

**Comment by smiths** [comment]
@LeilaMousapour, I agree with both you and @shmouses.  :smile:  You should avoid the details of the math for the BEM and the inverse calculations.  There could be an entire SRS devoted to each of these topics on its own.  Treating them as black boxes is fine.  However, after reading your SRS, I feel that you still need some more connections between your boxes.  If you can more clearly say what the input and output is from each box, then the inside of the box isn't relevant.  With clear input and output the connections between the boxes can become clear.  I've written some specific comments to get your started on my review of your SRS.
