### ISSUE TITLE
Question about physical system

### ISSUE THREAD

**Issue by shmouses** [LeilaMousapour/Brain-Computer-Interface-#9]
Hi @LeilaMousapour, 
I was wondering to ask if the level of detail you have in your physical system is necessary or not? For instance as is demonstrated in the figure here you have elements such as "Head" in your list. So, is head really a physical system? or its presence is already reflected in the other elements you have here such as EEG signal, EEG locations, head MRI results, and neurological activity of the brain.

![Screenshot from 2020-10-26 19-28-16](https://user-images.githubusercontent.com/49411064/97239454-0cc0fa80-17c2-11eb-8855-baf55e99d347.png)

**Comment by smiths** [comment]
@LeilaMousapour, I have not reviewed your SRS as of yet, but my instinct is that you do want to include the head as part of your physical system.  Your data collection revolves around the head.  You should definitely think about the concerns expressed by @shmouses.  Closing this issue may involve a written comment here, rather than actually changing your SRS.

**Comment by LeilaMousapour** [comment]
Thank you @shmouses  for this comment. I see your point. I should only include the "head" and "EEG equipment" as parts of the physical system. Fixed #c047177
